-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 21:32:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Music
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Music
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Music` DEFAULT CHARACTER SET utf8 ;
USE `Music` ;

-- -----------------------------------------------------
-- Table `Music`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music`.`Genre` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NOT NULL,
  `Region` VARCHAR(45) NOT NULL,
  `Year` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music`.`Bands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music`.`Bands` (
  `idBand` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Year` VARCHAR(45) NOT NULL,
  `BandMembers` INT NOT NULL,
  `Genre_ID` INT NOT NULL,
  PRIMARY KEY (`idBand`),
  INDEX `fk_Bands_Genre1_idx` (`Genre_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Bands_Genre1`
    FOREIGN KEY (`Genre_ID`)
    REFERENCES `Music`.`Genre` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music`.`LiveAppearances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music`.`LiveAppearances` (
  `idLive Appearances` INT NOT NULL AUTO_INCREMENT,
  `Location` VARCHAR(45) NOT NULL,
  `Year` INT NOT NULL,
  `Attendance` INT NOT NULL,
  `Bands_idBand` INT NOT NULL,
  PRIMARY KEY (`idLive Appearances`),
  INDEX `fk_Live Appearances_Bands1_idx` (`Bands_idBand` ASC) VISIBLE,
  CONSTRAINT `fk_Live Appearances_Bands1`
    FOREIGN KEY (`Bands_idBand`)
    REFERENCES `Music`.`Bands` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music`.`Albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music`.`Albums` (
  `idAlbums` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `ReleaseYear` INT NOT NULL,
  `Bands_idBand` INT NOT NULL,
  PRIMARY KEY (`idAlbums`),
  INDEX `fk_Music Instruments_Bands1_idx` (`Bands_idBand` ASC) VISIBLE,
  CONSTRAINT `fk_Music Instruments_Bands1`
    FOREIGN KEY (`Bands_idBand`)
    REFERENCES `Music`.`Bands` (`idBand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music`.`Songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music`.`Songs` (
  `idSongs` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Duration` INT NOT NULL,
  `Albums_idAlbums` INT NOT NULL,
  PRIMARY KEY (`idSongs`),
  INDEX `fk_Songs_Albums1_idx` (`Albums_idAlbums` ASC) VISIBLE,
  CONSTRAINT `fk_Songs_Albums1`
    FOREIGN KEY (`Albums_idAlbums`)
    REFERENCES `Music`.`Albums` (`idAlbums`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

insert into genre(Type,Region,Year)
values ("Rock","USA",1951),
 ("Metal","USA",1968),
  ("Punk","USA",1976),
   ("Pop","USA",1954);

insert into bands(Name,Year,BandMembers,Genre_ID)
 values ("Queen	", 1970	, 4, 1),
 ("Rolling Stones", 1962, 4, 1),
 ("The Beatles", 1960, 4, 1),
 ("Metallica	", 1982, 4, 2),
 ("Iron Maiden", 1975, 6, 2),
 ("Judas Priest", 1969, 5, 2),
 ("Ramones", 1974, 7, 3),
 ("The Clash", 1976, 10, 3),
 ("Dead Kennedys", 1978, 3, 3),
 ("Fleetwood Mac", 1967, 5, 4),
 ("U2", 1976, 4, 4),
 ("REM", 1980, 4, 4);
 
  insert into liveappearances(Location,Year,Attendance,Bands_idBand)
 values ("Rio De Janeiro, Brazil",1985,400000,1),
("Rio De Janeiro, Brazil",2006,1500000	,2),
("New York, USA",1965	,55000	,3),
("Moscow, Russia",1991,1600000,4),
("Rio De Janeiro, Brazil",1985,350000,5),
("Baltimore, USA",2016,256000,6),
("Buenos Aires, Argentina",1996,45000,7),
("London, UK",1996,70000,8),
("Sacramento, USA",1980,68000,9),
("London, UK",1967,32000,10),
("California, USA",2009,97000,11),
("Colorado, USA",1995,34000,12);

insert into albums(Name,ReleaseYear,Bands_idBand)
 values ("A Night At The Opera",1975,1),
 ("Queen",1973,1),
 ("Exile on Main Street",1972,2),
 ("Some Girls",1978,2),
 ("Revolver",1966,3),
 ("Abbey Road",1969,3),
 ("Master Of Puppets",1986,4),
 ("Ride The Lightning",1984,4),
 ("Powerslave",1984,5),
 ("The Number Of The Beast",1982,5),
 ("Screaming For Vengeance",1982,6),
 ("Sad Wings Of Destiny",1976,6),
 ("Rocket to Russia",1977,7),
 ("Ramones",1976,7),
 ("London Calling",1979,8),
 ("The Clash",1977,8),
 ("Fresh Fruit for Rotting Vegetables",1980,9),
 ("Plastic Surgery Disasters",1982,9),
 ("Rumours",1977,10),
 ("Fleetwood Mac",1975,10),
 ("Achtung Baby",1992,11),
 ("The Unforgettable Fire",1984,11),
 ("Reckoning",1984,12),
 ("Automatic For The People",1992,12);
 
 insert into songs(Name,Duration,Albums_idAlbums)
 values ("Bohemian Rhapsody",5.54,1),
 ("Love Of My Life",3.38,1),
 ("Keep Yourself Alive",3.47,2),
 ("Happy",3.05,3),
 ("Far Away Eyes",4.24,4),
 ("Some Girls",4.37,4),
 ("Yellow Submarine",2.4,5),
 ("Come Together",4.19,6),
 ("I Want You",7.47,6),
 ("Master of Puppets",8.35,7),
 ("Orion",8.12,7),
 ("Fade To Black",6.57,8),
 ("Aces High",4.32,9),
 ("The Number Of The Beast",4.51,10),
 ("Hallowed Be Thy Name",7.11,10),
 ("You've got Another Thing Coming",5.1,11),
 ("Dreamer Deceiver",5.56,12),
 ("Victim Of Changes",7.45,12),
 ("Locket Love",2.11,13),
 ("Blitzkrieg Bop",2.12,14),
 ("Loudmouth",2.15,14),
 ("London Calling",3.2,15),
 ("The Guns of Brixton",3.12,15),
 ("London’s Burning",2.11,16),
 ("California über alles",3.02,17),
 ("Holiday in Cambodia",4.33,17),
 ("Riot",5.57,18),
 ("The Chain",4.31,19),
 ("Go Your Own Way",3.39,19),
 ("Rhiannon",4.11,20),
 ("Love Is Blindness",4.24,21),
 ("Pride",3.49,22),
 ("Indian Summer Sky",4.19,22),
 ("Little America",5.19,23),
 ("Drive",4.25,24),
 ("Everybody Hurts",5.19,24);
